name: Frontend Testing
on:
    push:
        paths:
            - hyperglass/ui/**
            - .github/**
    pull_request:

jobs:
    frontend:
        name: Frontend Tests
        strategy:
            fail-fast: false
            matrix:
                node-version: [20.x, 21.x, 22.x]
                pnpm-version: [9, 10]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        env:
            working-directory: ./hyperglass/ui
        steps:
            - name: Git Checkout
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

            - name: Install Node
              uses: actions/setup-node@49933ea5288caeca8642195f2b846b8bbe245a93 # v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install PNPM
              uses: pnpm/action-setup@v3
              with:
                  version: ${{ matrix.pnpm-version }}

            - name: Install Dependencies
              working-directory: ${{ env.working-directory }}
              run: pnpm install

            - name: Create empty hyperglass.json
              working-directory: ${{ env.working-directory }}
              run: echo '{}' > hyperglass.json

            - name: Formatting
              working-directory: ${{ env.working-directory }}
              run: pnpm run format:check

            - name: Lint
              working-directory: ${{ env.working-directory }}
              run: pnpm run lint

            - name: Check Types
              working-directory: ${{ env.working-directory }}
              run: pnpm run typecheck

            - name: Tests
              working-directory: ${{ env.working-directory }}
              run: pnpm run test
